executors:
  notebook-executor:
    docker:
    - image: continuumio/miniconda3
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Asdf Example:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n asdf_example
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n asdf_example
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Background Estimation Imaging:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n background_estimation_imaging
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n background_estimation_imaging
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Cube Fitting:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n cube_fitting
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n cube_fitting
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Miri Lrs Spectral Extraction:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n MIRI_LRS_spectral_extraction
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n MIRI_LRS_spectral_extraction
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Mos-Spectroscopy:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n mos-spectroscopy
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n mos-spectroscopy
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Mrs Mstar Analysis:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n MRS_Mstar_analysis
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n MRS_Mstar_analysis
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Nircam Photometry:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n NIRCam_photometry
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n NIRCam_photometry
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Niriss Wfss Postpipeline:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n NIRISS_WFSS_postpipeline
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n NIRISS_WFSS_postpipeline
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Optimal Extraction:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n optimal_extraction
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n optimal_extraction
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Psf Photometry:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n psf_photometry
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n psf_photometry
        name: Build Website
    - store_artifacts:
        path: ./pages
  Jdat Notebooks-Transit Spectroscopy Notebook:
    environment:
      PYTHONPATH: .circleci
    executor: notebook-executor
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup_env.sh
        name: Setup Environment
    - run:
        command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks
          -n transit_spectroscopy_notebook
        name: Build Notebook
        no_output_timeout: 60m
    - run:
        command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks
          -n transit_spectroscopy_notebook
        name: Build Website
    - store_artifacts:
        path: ./pages
version: 2.1
workflows:
  Branch Build:
    jobs:
    - Jdat Notebooks-Psf Photometry
    - Jdat Notebooks-Nircam Photometry
    - Jdat Notebooks-Asdf Example
    - Jdat Notebooks-Transit Spectroscopy Notebook
    - Jdat Notebooks-Background Estimation Imaging
    - Jdat Notebooks-Cube Fitting
    - Jdat Notebooks-Optimal Extraction
    - Jdat Notebooks-Miri Lrs Spectral Extraction
    - Jdat Notebooks-Mrs Mstar Analysis
    - Jdat Notebooks-Niriss Wfss Postpipeline
    - Jdat Notebooks-Mos-Spectroscopy
  version: '2.1'
